openapi: 3.0.3
info:
  title: Maxblog Main API
  description: |-
    Maxblog主站API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: demo
    description: 主站样例页面API
paths:
  /demo:
    get:
      tags:
        - demo
      description: GET 样例页面数据
      parameters:
        - name: count
          in: query
          description: 鼠标滚轮到底次数
          required: false
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemoData'
        500:
          description: fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Http500Response'
  /demo/{id}:
    get:
      tags:
        - demo
      description: 根据id查找样例
      parameters:
        - name: id
          in: path
          description: ID of demo
          required: true
          schema:
            type: integer
            format: int32
            example: 1
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demo'
        500:
          description: fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Http500Response'
components:
  schemas:
    DemoData:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
              format: int32
              example: 0
            desc:
              type: string
              example: success
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
                example: 1
              title:
                type: string
                example: Luxun
              desc:
                type: string
                example: 这是一个简介
              createdAt:
                type: string
                format: date-time
                example: 2019-10-12T07:20:50.52Z
              preview:
                type: string
                example: https://maxblog.com/static/demo/1
              view:
                type: integer
                format: int32
                example: 10
    Demo:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              type: integer
              format: int32
              example: 0
            desc:
              type: string
              example: success
        data:
          type: object
          properties:
            id:
              type: integer
              format: int32
              example: 1
            title:
              type: string
              example: Luxun
            desc:
              type: string
              example: 这是一个简介
            createdAt:
              type: string
              format: date-time
              example: 2019-10-12T07:20:50.52Z
            content:
              type: string
              example: 具体代码
            view:
              type: integer
              format: int32
              example: 10
            ref:
              type: string
              example: 参考url
    Http500Response:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              format: int32
              example: 999
            desc:
              type: string
              example: null



  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Demo'


  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header